// Données de démonstration pour la boutique AssiaSweet
// Utilisées quand l'API n'est pas disponible (mode web preview / CORS)

import type { Product, Category, Slider, CartItem } from "./types";

export const DEMO_SLIDERS: Slider[] = [
  {
    id: "s1",
    title: "Nouveautés Printemps 2025",
    subtitle: "Découvrez nos dernières confiseries",
    image_url: "https://images.unsplash.com/photo-1582058091597-35b2e7a36e7a?w=800&q=80",
    sort_order: 1,
    is_active: true,
  },
  {
    id: "s2",
    title: "Bonbons Halal",
    subtitle: "Certifiés halal — Large sélection",
    image_url: "https://images.unsplash.com/photo-1621939514649-280e2ee25f60?w=800&q=80",
    sort_order: 2,
    is_active: true,
  },
  {
    id: "s3",
    title: "Livraison GLS 24-48h",
    subtitle: "Commande min. 100€ HT",
    image_url: "https://images.unsplash.com/photo-1499195333224-3ce974eecb47?w=800&q=80",
    sort_order: 3,
    is_active: true,
  },
];

export const DEMO_CATEGORIES: Category[] = [
  { id: "c1", name: "Bonbons", slug: "bonbons", isActive: true },
  { id: "c2", name: "Chocolats", slug: "chocolats", isActive: true },
  { id: "c3", name: "Chewing-gums", slug: "chewing-gums", isActive: true },
  { id: "c4", name: "Sucettes", slug: "sucettes", isActive: true },
  { id: "c5", name: "Guimauves", slug: "guimauves", isActive: true },
  { id: "c6", name: "Réglisses", slug: "reglisses", isActive: true },
  { id: "c7", name: "Caramels", slug: "caramels", isActive: true },
  { id: "c8", name: "Halal", slug: "halal", isActive: true },
];

const HARIBO_BRAND = { id: "b1", name: "Haribo", slug: "haribo", isActive: true };
const FINI_BRAND = { id: "b2", name: "Fini", slug: "fini", isActive: true };
const CHUPA_BRAND = { id: "b3", name: "Chupa Chups", slug: "chupa-chups", isActive: true };
const MENTOS_BRAND = { id: "b4", name: "Mentos", slug: "mentos", isActive: true };
const CARAMBAR_BRAND = { id: "b5", name: "Carambar", slug: "carambar", isActive: true };

const BONBONS_CAT = { id: "c1", name: "Bonbons", slug: "bonbons", isActive: true };
const HALAL_CAT = { id: "c8", name: "Halal", slug: "halal", isActive: true };
const SUCETTES_CAT = { id: "c4", name: "Sucettes", slug: "sucettes", isActive: true };
const CHEWING_CAT = { id: "c3", name: "Chewing-gums", slug: "chewing-gums", isActive: true };
const CARAMELS_CAT = { id: "c7", name: "Caramels", slug: "caramels", isActive: true };
const GUIMAUVES_CAT = { id: "c5", name: "Guimauves", slug: "guimauves", isActive: true };

export const DEMO_PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "Haribo Goldbears 1kg",
    slug: "haribo-goldbears-1kg",
    brand: HARIBO_BRAND,
    description: "Les célèbres oursons en gélatine Haribo. Sachet de 1kg idéal pour la revente.",
    priceHT: 4.90,
    price: 4.90,
    tva: 5.5,
    stock: 250,
    inStock: true,
    isHalal: false,
    isVegan: false,
    isSugarFree: false,
    isNew: false,
    isPromo: false,
    images: ["https://images.unsplash.com/photo-1582058091597-35b2e7a36e7a?w=400&q=80"],
    image: "https://images.unsplash.com/photo-1582058091597-35b2e7a36e7a?w=400&q=80",
    category: BONBONS_CAT,
    status: "ACTIVE",
    trackStock: true,
    barcode: "4001686325162",
  },
  {
    id: "p2",
    name: "Tagada Fraise 1kg",
    slug: "tagada-fraise-1kg",
    brand: HARIBO_BRAND,
    description: "Les fraises Tagada, best-seller incontournable. Sachet de 1kg.",
    priceHT: 4.50,
    price: 4.50,
    tva: 5.5,
    stock: 180,
    inStock: true,
    isHalal: false,
    isVegan: false,
    isSugarFree: false,
    isNew: false,
    isPromo: true,
    images: ["https://images.unsplash.com/photo-1621939514649-280e2ee25f60?w=400&q=80"],
    image: "https://images.unsplash.com/photo-1621939514649-280e2ee25f60?w=400&q=80",
    category: BONBONS_CAT,
    status: "ACTIVE",
    trackStock: true,
    barcode: "4001686325179",
  },
  {
    id: "p3",
    name: "Bonbons Halal Mix 1kg",
    slug: "bonbons-halal-mix-1kg",
    brand: FINI_BRAND,
    description: "Assortiment de bonbons certifiés halal. Idéal pour épiceries halal.",
    priceHT: 6.50,
    price: 6.50,
    tva: 5.5,
    stock: 120,
    inStock: true,
    halal: true,
    isHalal: true,
    isVegan: false,
    isSugarFree: false,
    isNew: true,
    isPromo: false,
    images: ["https://images.unsplash.com/photo-1499195333224-3ce974eecb47?w=400&q=80"],
    image: "https://images.unsplash.com/photo-1499195333224-3ce974eecb47?w=400&q=80",
    category: HALAL_CAT,
    status: "ACTIVE",
    trackStock: true,
    barcode: "8410525020010",
  },
  {
    id: "p4",
    name: "Chupa Chups Assortis x200",
    slug: "chupa-chups-assortis-x200",
    brand: CHUPA_BRAND,
    description: "Boîte de 200 sucettes Chupa Chups aux parfums assortis.",
    priceHT: 28.90,
    price: 28.90,
    tva: 5.5,
    stock: 45,
    inStock: true,
    isHalal: false,
    isVegan: false,
    isSugarFree: false,
    isNew: false,
    isPromo: false,
    images: ["https://images.unsplash.com/photo-1567206563064-6f60f40a2b57?w=400&q=80"],
    image: "https://images.unsplash.com/photo-1567206563064-6f60f40a2b57?w=400&q=80",
    category: SUCETTES_CAT,
    status: "ACTIVE",
    trackStock: true,
    barcode: "8410500000000",
  },
  {
    id: "p5",
    name: "Dragibus Soft 1kg",
    slug: "dragibus-soft-1kg",
    brand: HARIBO_BRAND,
    description: "Les Dragibus Soft en sachet de 1kg. Texture moelleuse et couleurs vives.",
    priceHT: 5.80,
    price: 5.80,
    tva: 5.5,
    stock: 95,
    inStock: true,
    isHalal: false,
    isVegan: false,
    isSugarFree: false,
    isNew: true,
    isPromo: false,
    images: ["https://images.unsplash.com/photo-1581798459219-318e76aecc7b?w=400&q=80"],
    image: "https://images.unsplash.com/photo-1581798459219-318e76aecc7b?w=400&q=80",
    category: BONBONS_CAT,
    status: "ACTIVE",
    trackStock: true,
    barcode: "4001686325186",
  },
  {
    id: "p6",
    name: "Mentos Menthe x40",
    slug: "mentos-menthe-x40",
    brand: MENTOS_BRAND,
    description: "Carton de 40 rouleaux Mentos menthe fraîche.",
    priceHT: 16.00,
    price: 16.00,
    tva: 5.5,
    stock: 60,
    inStock: true,
    isHalal: false,
    isVegan: false,
    isSugarFree: false,
    isNew: false,
    isPromo: true,
    images: ["https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400&q=80"],
    image: "https://images.unsplash.com/photo-1544145945-f90425340c7e?w=400&q=80",
    category: CHEWING_CAT,
    status: "ACTIVE",
    trackStock: true,
    barcode: "8000500000000",
  },
  {
    id: "p7",
    name: "Carambar Caramel x200",
    slug: "carambar-caramel-x200",
    brand: CARAMBAR_BRAND,
    description: "Boîte de 200 Carambar caramel, la blague dans chaque emballage.",
    priceHT: 14.90,
    price: 14.90,
    tva: 5.5,
    stock: 80,
    inStock: true,
    isHalal: false,
    isVegan: false,
    isSugarFree: false,
    isNew: false,
    isPromo: false,
    images: ["https://images.unsplash.com/photo-1587132137056-bfbf0166836e?w=400&q=80"],
    image: "https://images.unsplash.com/photo-1587132137056-bfbf0166836e?w=400&q=80",
    category: CARAMELS_CAT,
    status: "ACTIVE",
    trackStock: true,
    barcode: "3017620000000",
  },
  {
    id: "p8",
    name: "Guimauve Chamallow 300g",
    slug: "guimauve-chamallow-300g",
    brand: HARIBO_BRAND,
    description: "Chamallows Haribo en sachet de 300g. Doux et moelleux.",
    priceHT: 2.90,
    price: 2.90,
    tva: 5.5,
    stock: 200,
    inStock: true,
    isHalal: false,
    isVegan: false,
    isSugarFree: false,
    isNew: false,
    isPromo: false,
    images: ["https://images.unsplash.com/photo-1559598467-f8b76c8155d0?w=400&q=80"],
    image: "https://images.unsplash.com/photo-1559598467-f8b76c8155d0?w=400&q=80",
    category: GUIMAUVES_CAT,
    status: "ACTIVE",
    trackStock: true,
    barcode: "4001686325193",
  },
  {
    id: "p9",
    name: "Réglisse Zan x100",
    slug: "reglisse-zan-x100",
    brand: { id: "b6", name: "Zan", slug: "zan", isActive: true },
    description: "Boîte de 100 pastilles de réglisse Zan. Goût intense et authentique.",
    priceHT: 12.50,
    price: 12.50,
    tva: 5.5,
    stock: 55,
    inStock: true,
    isHalal: false,
    isVegan: true,
    isSugarFree: false,
    isNew: false,
    isPromo: false,
    images: ["https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&q=80"],
    image: "https://images.unsplash.com/photo-1563805042-7684c019e1cb?w=400&q=80",
    category: { id: "c6", name: "Réglisses", slug: "reglisses", isActive: true },
    status: "ACTIVE",
    trackStock: true,
    barcode: "3017620000001",
  },
  {
    id: "p10",
    name: "Kinder Bueno x30",
    slug: "kinder-bueno-x30",
    brand: { id: "b7", name: "Kinder", slug: "kinder", isActive: true },
    description: "Carton de 30 Kinder Bueno. Biscuit croustillant et crème noisette.",
    priceHT: 22.90,
    price: 22.90,
    tva: 5.5,
    stock: 40,
    inStock: true,
    isHalal: false,
    isVegan: false,
    isSugarFree: false,
    isNew: false,
    isPromo: false,
    images: ["https://images.unsplash.com/photo-1575377427642-087cf684ad4b?w=400&q=80"],
    image: "https://images.unsplash.com/photo-1575377427642-087cf684ad4b?w=400&q=80",
    category: { id: "c2", name: "Chocolats", slug: "chocolats", isActive: true },
    status: "ACTIVE",
    trackStock: true,
    barcode: "8000500000001",
  },
];

export const DEMO_CART_ITEMS: CartItem[] = [
  {
    productId: "p1",
    productName: "Haribo Goldbears 1kg",
    brand: "Haribo",
    unitPriceHT: 4.90,
    tvaRate: 5.5,
    quantity: 6,
    productImage: "https://images.unsplash.com/photo-1582058091597-35b2e7a36e7a?w=400&q=80",
  },
  {
    productId: "p3",
    productName: "Bonbons Halal Mix 1kg",
    brand: "Fini",
    unitPriceHT: 6.50,
    tvaRate: 5.5,
    quantity: 4,
    productImage: "https://images.unsplash.com/photo-1499195333224-3ce974eecb47?w=400&q=80",
  },
];
